### ISSUE TITLE
Yesod Book is now NC-ND licensed‽

### ISSUE THREAD

**Issue by wolftune** [yesodweb/yesodweb.com-content#126]
Was that something O'Reilly insisted upon? I was thinking of eventually contributing some improvements to the book, but now I'm not even allowed to use the material freely, and that's discouraging. NC is already non-free, but ND is additional restriction. That's an unfortunate mark, although I suppose it's true that there's at least the Haddock for the exact Yesod code, but the Yesod Book is otherwise the plain core documentation…

I'm not sure making this ticket is appropriate, but just wanted to clarify and understand the situation. I find it quite unfortunate. I suspect that the NC-ND terms do not actually lead to even the tiniest increase in sales or otherwise achieve anything positive whatsoever…

Thanks otherwise for all the great work on the software and licensing the rest of the site freely.

**Comment by snoyberg** [comment]
It was insisted upon by O'Reilly. It actually was in the agreements I'd already signed, so there's actually nothing I can do about it. I would recommend you pass your message along to O'Reilly, it might impact their feelings in things. They're a very open minded group if people.

**Comment by wolftune** [comment]
Ok thanks for the note, sincerely appreciated. I'll consider making the case to O'Reilly.

**Comment by wolftune** [comment]
I ended up encountering an O'Reilly person in an unrelated circumstance and mentioned this issue, and he pushed me to see it through… According to an O'Reilly lawyer today, they're willing to allow the online documentation on the site and on GitHub to have the free/libre/open CC-BY licensing. Maybe they're keeping the restrictive license for the formal O'Reilly publication, I don't know and don't much care as long as the primary documentation is freely-licensed. So, yay! Looking forward to seeing the update reverting to having all the Yesod site under the same consistent and Free/Open licensing. :)

**Comment by snoyberg** [comment]
I signed some paperwork with O'Reilly about changing the license, but
haven't heard a solid response. I can query them, but do you want to send a
PR for the relevant license file changes in the interim?

**Comment by wolftune** [comment]
I could submit a PR, but I wasn't clear whether the book content will be the MIT & CC-BY dual license fully matching all other content or if it will be only CC-BY (I can't imagine O'Reilly would care that much, but CC-BY was the only one the O'Reilly lawyer mentioned in the email to me).

**Comment by snoyberg** [comment]
Creative Commons Attribution 4.0 International License

**Comment by snoyberg** [comment]
IIRC, this was fully resolved with O'Reilly, closing.

**Comment by wolftune** [comment]
confirmed, thanks again
