### ISSUE TITLE
Zoom broken on Safari

### ISSUE THREAD

**Issue by eallik** [yesodweb/yesodweb.com-content#129]
the web site goes berserk when Cmd-+ or Cmd-- is pressed for about 3-4 seconds, and then normalizes. It makes zooming in and out very inconvenient! I guess there's a JS component on the web site trying to make zoom animated, which is causing this?

**Comment by snoyberg** [comment]
I don't have access to a Safari machine to test this on. I'm not sure which component could be causing it. Does this occur on all pages of the site?

**Comment by eallik** [comment]
not for example on the main page but definitely on the tutorial page; it's driving me nuts :)

**Comment by snoyberg** [comment]
Closing out old issues, if still relevant please open a new one.
