### ISSUE TITLE
Getting Rating A from the SSL Server Test

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/yesodweb.com-content#136]
I wrote a new blog article: https://github.com/yesodweb/yesodweb.com-content/blob/master/blog/2015/08/ssl-server-test.md

@snoyberg May I ask to correct my broken English?

@AaronFriel Would you check your part?

@snoyberg This markdown included hard-coded color information. Colors are ignored when viewing on github. What about yesod.com? Can we see red/orange/green text?

**Comment by snoyberg** [comment]
I'll review content now. Just wanted to comment: the color information is preserved on yesodweb.com

**Comment by kazu-yamamoto** [comment]
@snoyberg Thank you for confirming and reviewing! I should have used spell checker more carefully.

**Comment by kazu-yamamoto** [comment]
The article is now published.

**Comment by AaronFriel** [comment]
Thank you for crediting me, although I really did only a small amount of work. The `tls` library made it very easy to add the missing ciphers. Apologies for not reviewing this promptly!
