### ISSUE TITLE
Deployment chapter makes no mention of Stack

### ISSUE THREAD

**Issue by magnusmorton** [yesodweb/yesodweb.com-content#140]
The deployment chapter perhaps could be updated to show how a deployment workflow with Stack could work. Even nicer would be a Stack + Docker workflow

**Comment by snoyberg** [comment]
I'll probably be able to get to this in the next few weeks, but a PR would definitely be appreciated.

**Comment by m-renaud** [comment]
Cabal is still mentioned in the "Scaffolding and the Site Template" chapter, should converting this to use the Yesod templates for stack be part of this bug or should another bug be opened for that? In either case, can this bug be closed now?

**Comment by snoyberg** [comment]
Yeah, good catch, this can be closed. A new issue (or better, PR) for fixing the scaffolding chapter would be much appreciated!
