### ISSUE TITLE
O'Reilly ebook update cycle?

### ISSUE THREAD

**Issue by kairuku** [yesodweb/yesodweb.com-content#145]
Hi Michael,

I was wondering how often O'Reilly updates the ebook versus the current online version of the Yesod book (I noticed in my O'Reilly account the last update date is in March). Is it just from one major version (e.g., 1.4 to 1.5) or something like that, or can they update it real time even with minor updates to the framework and the online version of the book?

Is there anything like a private repo for subscribers to get regenerated PDF's?

Thanks :)

**Comment by snoyberg** [comment]
There is no official release timing cycle on the PDF version of the book
from O'Reilly.

**Comment by kairuku** [comment]
Are there any significant deviations between the PDF and the current version of the web edition to be aware of?

**Comment by snoyberg** [comment]
Nothing significant that I'm aware of, though you can check the history in Git to see changes that have been made since publication.

**Comment by kairuku** [comment]
Thank you for the feedback.
