### ISSUE TITLE
Link on "Wiki: markdown, chat subsite, event source" is broken

### ISSUE THREAD

**Issue by amitaibu** [yesodweb/yesodweb.com-content#172]
The link from [this](https://github.com/yesodweb/yesodweb.com-content/blob/341db45b4f42eb6a773ef741fbdb7f666dbdbae2/book/asciidoc/wiki-chat-example.asciidoc#wiki-markdown-chat-subsite-event-source) page -  https://www.schoolofhaskell.com/user/snoyberg/yesod/wiki-markdown-chat-subsite-event-source doesn't seem to work.

**Comment by snoyberg** [comment]
Thanks! In the future, feel free to send a PR for such fixes.

**Comment by amitaibu** [comment]
Sure, I just didn't know if those links were dead or not .

**Comment by snoyberg** [comment]
God it
