### ISSUE TITLE
The type YesodDB in the persistent chapter is wrong.

### ISSUE THREAD

**Issue by kbr-** [yesodweb/yesodweb.com-content#174]
It didn't make sense to me:
type YesodDB site = YesodPersistBackend site (HandlerT site IO)
since "YesodPersistBackend site" already has kind *.

> *Main Lib Database.Persist.Sqlite Yesod> :i YesodDB
> type YesodDB site =
>   transformers-0.4.2.0:Control.Monad.Trans.Reader.ReaderT
>     (YesodPersistBackend site) (HandlerT site IO)
>   	-- Defined in ‘yesod-persistent-1.4.0.5:Yesod.Persist.Core’

**Comment by snoyberg** [comment]
Good catch, thanks! In the future, feel free to send a PR to make such updates.

**Comment by kbr-** [comment]
Great, thanks. Will do.
