### ISSUE TITLE
Add attributes to nested route

### ISSUE THREAD

**Issue by maxigit** [yesodweb/yesodweb.com-content#175]
I'm not sure if it's the right place to suggest this, so I apologize it is not.
Having playing with  route attributes and hierarchical route and I discover that you It works as excepted, ie , children inherists from parent attributes. However, the syntax is no that straight forward, as the colon needs to be after the attributes. e.g,

/admin AdminR !admin:
   /1 Admin1R !a
   /2 Admin2R !b

then `routeAttrs (Admin1R)` returns `fromList ("admin", "a").

It's a really cool feature which I think could be addd in the route attributes pages.

**Comment by snoyberg** [comment]
That sounds good, interested in sending a PR to add such content?

**Comment by maxigit** [comment]
I can try. Should I modify the route attributes page ?

**Comment by snoyberg** [comment]
Sure, sounds good. Just update the asciidoc

**Comment by maxigit** [comment]
Just checking if you've seen the update to the pull request.

**Comment by snoyberg** [comment]
No, I hadn't, thanks!
