### ISSUE TITLE
Yesod book website is down

### ISSUE THREAD

**Issue by psibi** [yesodweb/yesodweb.com-content#178]
![yesod-book](https://cloud.githubusercontent.com/assets/737477/18426506/c38d00be-78df-11e6-81f5-e80988e68205.png)

**Comment by snoyberg** [comment]
Thanks, I've fixed the broken markup and am adding a validate step to the Travis job. I hadn't realized that AsciiDoc would sometimes generated invalid XML, that's kind of shocking.
