### ISSUE TITLE
Incorrect formatting of code

### ISSUE THREAD

**Issue by chrissound** [yesodweb/yesodweb.com-content#189]
https://www.yesodweb.com/book/persistent

![2017-04-02-18 05 14](https://cloud.githubusercontent.com/assets/1499652/24589238/17eb445c-17cf-11e7-9e83-b652963f19a2.png)

The above has code that appears as two lines instead of one.

It should appear like this (a single line)
`share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|`

**Comment by snoyberg** [comment]
I've modified the CSS so that code blocks scroll instead of wrap, can you check it out?

**Comment by chrissound** [comment]
All fixed! Thank you
