### ISSUE TITLE
Mention https://github.com/yesodweb/persistent/wiki in book

### ISSUE THREAD

**Issue by dfordivam** [yesodweb/yesodweb.com-content#190]
Some where mention this wiki as a useful resource for more information.
(at the end of this probably) 
https://github.com/yesodweb/persistent/wiki/Persistent-entity-syntax

I had to spend a considerable time in search of this...
And when I gave up on google, and started browsing the code I got a reference to this Wiki

**Comment by snoyberg** [comment]
Can you send a PR to add the mention?
