### ISSUE TITLE
Nginx welcome page showing up on https://www.yesodweb.com/

### ISSUE THREAD

**Issue by chrissound** [yesodweb/yesodweb.com-content#192]
http://www.haskellers.com/ as well if it's helpful

**Comment by snoyberg** [comment]
Thanks for the heads-up, should be fixed now.

**Comment by chrissound** [comment]
Just checked and doesn't appear to be? 
It's only via https://www.yesodweb.com (which shows up on Google)

**Comment by snoyberg** [comment]
Try going to the non-secure URL (http://), secure isn't properly activated.
I'll see about fixing that.
