### ISSUE TITLE
Error following through with Form section

### ISSUE THREAD

**Issue by chrissound** [yesodweb/yesodweb.com-content#193]
`Not in scope: type constructor or class ‘Widget’`

http://www.yesodweb.com/book/forms

`personForm :: Html -> MForm Handler (FormResult Person, Widget)`

Is this possibly outdated?

**Comment by psibi** [comment]
I think it's a type synonym of `WidgetT`: `type Widget = WidgetT App IO ()` ...

**Comment by snoyberg** [comment]
Correct, and it's automatically generated by the mkYesod call. The example
works on my machine.

**Comment by chrissound** [comment]
Ah, makes sense. Thank you
