### ISSUE TITLE
Yesod Book 1.4 --> 1.6

### ISSUE THREAD

**Issue by pythonissam** [yesodweb/yesodweb.com-content#204]
Tutorials doesn't deal with Yesod 1.6 and some examples don't run properly. For example: [Creating a Subsite](https://www.yesodweb.com/book/creating-a-subsite). Can I update this page so as to deal with v1.6 at least?

**Comment by snoyberg** [comment]
It would be great if you could send a PR to get a 1.6 branch of this repo started!

**Comment by pythonissam** [comment]
I'll try:)

**Comment by snoyberg** [comment]
PR merged, thanks!
