### ISSUE TITLE
backslash in ^ escaping example missing in on-line version

### ISSUE THREAD

**Issue by gimbiss** [yesodweb/yesodweb.com-content#224]
The asciidoc file has the backslash:  
 backslash can be used to prevent the interpolation,
  e.g. +[lt|2^\{23}|]+. The backslash is removed from the resulting text.

but the backslash does not show on the page:
https://www.yesodweb.com/book/shakespearean-templates

![image](https://user-images.githubusercontent.com/37869731/48366597-11fd0b80-e6b7-11e8-8abb-315bfdd24562.png)

**Comment by gimbiss** [comment]
well I see the backslash disappeared above also.
here is a screenshot of the gitub edit page for the asciidoc (to show that I am not crazy):
![image](https://user-images.githubusercontent.com/37869731/48366764-79b35680-e6b7-11e8-8d10-ade03d6eda71.png)

**Comment by snoyberg** [comment]
Thanks for the report, this should be fixed now.
