### ISSUE TITLE
Possible mismatch between text and code example

### ISSUE THREAD

**Issue by eahlberg** [yesodweb/yesodweb.com-content#259]
I noticed a possible mismatch between the text and the code example under [Subsite: handlers](https://github.com/yesodweb/yesodweb.com-content/blob/master/book/asciidoc/wiki-chat-example.asciidoc#subsite-handlers). The paragraph which starts with `The call to runInputGet is a little more subtle` mentions `lift`, but `lift` is not used in the line I think it refers to, namely:
```
body <- runInputGet $ ireq textField "message"
```

It seems like a [previous version of the example](https://github.com/yesodweb/yesodweb.com-content/blame/0a417d42025a73b1839b784f5c6ed61a22f08fc3/book/asciidoc/wiki-chat-example.asciidoc#L120)  used lift, but I'm not sure why it was dropped.

I think it'd be beneficial if the usage of lift was either re-introduced or if the paragraph was dropped. However, if the paragraph is dropped, it might also be the case that the `RenderMessage` constraint on the `YesodChat` typeclass is unnecessary, meaning that there are more code examples that might need to be updated.

Any thoughts? I'd be glad to add a PR with the requested change.

**Comment by snoyberg** [comment]
The `RenderMessage` constraint is still necessary, but in Yesod 1.6 the API changed so that the `lift`s aren't necessary. A PR to remove the paragraph would be great!
