### ISSUE TITLE
PersistField vs. PersistValue

### ISSUE THREAD

**Issue by StevenXL** [yesodweb/yesodweb.com-content#262]
Hi folks. 

I accidentally pushed a [commit to master](https://github.com/yesodweb/yesodweb.com-content/commit/c54492cfe1bd799c6505a89ce74741b3c7c96467), when my intention was to open a PR for discussion. 

Rather than trying to undo what I did, I thought it would be best to bring attention to the change, and if it is not appropriate, we can discuss how to undo the change (open a PR w/ a revert commit).

In essence, I changed the language from _A +PersistField+ correlates to a
column in a SQL database. In our person example above, name and age would be
our ++PersistField++s_ to _A +PersistValue+ correlates to a column in a SQL database. In our person example
above, name and age would be our ++PersistValues++s_. 

Saying that a `PersistField` correlates to a column in our database is confusing, as it gives the impression that, for a data type such as `data Person = Person {personName :: String, personAge :: Maybe Int}`, there exists instances of `PersistField` for `personName` and `personAge`. (Which further implies we've generated data types for the fields, but I think even w/o this elaboration, the point of confusion stands). 

LMK what you all think.

**Comment by snoyberg** [comment]
Looks good to me, not objections. Thanks! I'm fine leaving as is and closing this issue if you are :)
