### ISSUE TITLE
Yesod Typeclass docs incorrectly say "The default value of approot is ApprootRelative"

### ISSUE THREAD

**Issue by jfly** [yesodweb/yesodweb.com-content#270]
From https://www.yesodweb.com/book/yesod-typeclass#yesod-typeclass_rendering_and_parsing_urls:

> The default value of approot is ApprootRelative, which essentially means “don’t add any prefix.”

I don't think this is true anymore. The [hackage docs](https://hackage.haskell.org/package/yesod-core-1.6.24.0/docs/Yesod-Core.html#v:approot) have this to say about `approot`:

> Default value: [guessApproot](https://hackage.haskell.org/package/yesod-core-1.6.24.0/docs/Yesod-Core.html#v:guessApproot). If you know your application root statically, it will be more efficient and more reliable to instead use [ApprootStatic](https://hackage.haskell.org/package/yesod-core-1.6.24.0/docs/Yesod-Core.html#v:ApprootStatic) or [ApprootMaster](https://hackage.haskell.org/package/yesod-core-1.6.24.0/docs/Yesod-Core.html#v:ApprootMaster). If you do not need full absolute URLs, you can use [ApprootRelative](https://hackage.haskell.org/package/yesod-core-1.6.24.0/docs/Yesod-Core.html#v:ApprootRelative) instead.
>
> Note: Prior to yesod-core 1.5, the default value was [ApprootRelative](https://hackage.haskell.org/package/yesod-core-1.6.24.0/docs/Yesod-Core.html#v:ApprootRelative).

**Comment by snoyberg** [comment]
You're correct, it's a change that's not reflected. Would you be up for sending a PR to clarify that?

**Comment by jfly** [comment]
On it!
